name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code...
        uses: actions/checkout@v1

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose